openapi: 3.0.3
info:
  title: Berry Buddy API
  version: "0.1.0"
  description: |
    A minimal API that fronts Supabase Postgres and forces all CRUD through the API.
    Authenticate with Supabase, then call endpoints with `Authorization: Bearer <JWT>`.
servers:
  - url: http://localhost:8080
    description: Local dev
tags:
  - name: Health
  - name: Profiles
  - name: Berries
  - name: Vendors
  - name: Prices
  - name: Reviews
  - name: Photos
paths:
  /health:
    get:
      tags: [Health]
      summary: Health check (no auth)
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  now: { type: string, format: date-time }
  /profiles/me:
    get:
      tags: [Profiles]
      summary: Get my profile
      responses:
        '200':
          description: Profile found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AppProfile' }
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [Profiles]
      summary: Upsert my profile
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                display_name: { type: string, minLength: 1, maxLength: 120 }
                location_city: { type: string }
                location_state: { type: string }
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AppProfile' }
  /berries:
    get:
      tags: [Berries]
      summary: List berries
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Array of berries
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Berry' }
    post:
      tags: [Berries]
      summary: Create berry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [berry_name]
              properties:
                berry_name: { type: string, minLength: 1, maxLength: 100 }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Berry' }
  /berries/{id}:
    get:
      tags: [Berries]
      summary: Get berry by id
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Berry' }
        '404': { $ref: '#/components/responses/NotFound' }
    patch:
      tags: [Berries]
      summary: Update berry
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                berry_name: { type: string, minLength: 1, maxLength: 100 }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Berry' }
        '404': { $ref: '#/components/responses/NotFound' }
    delete:
      tags: [Berries]
      summary: Delete berry
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Berry' }
        '404': { $ref: '#/components/responses/NotFound' }
  /vendors:
    get:
      tags: [Vendors]
      summary: List vendors
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Array of vendors
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Vendor' }
    post:
      tags: [Vendors]
      summary: Create vendor
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/VendorCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Vendor' }
  /vendors/{id}:
    get:
      tags: [Vendors]
      summary: Get vendor by id
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Vendor' }
        '404': { $ref: '#/components/responses/NotFound' }
    patch:
      tags: [Vendors]
      summary: Update vendor
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/VendorUpdate' }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Vendor' }
        '404': { $ref: '#/components/responses/NotFound' }
    delete:
      tags: [Vendors]
      summary: Delete vendor
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Vendor' }
        '404': { $ref: '#/components/responses/NotFound' }
  /prices:
    get:
      tags: [Prices]
      summary: List prices
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Array of prices
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Price' }
    post:
      tags: [Prices]
      summary: Create price (reported_by = current user)
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PriceCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Price' }
  /prices/{id}:
    patch:
      tags: [Prices]
      summary: Update price (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PriceUpdate' }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Price' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
    delete:
      tags: [Prices]
      summary: Delete price (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Price' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /reviews:
    get:
      tags: [Reviews]
      summary: List reviews
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Array of reviews
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Review' }
    post:
      tags: [Reviews]
      summary: Create review (reported_by = current user)
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ReviewCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Review' }
  /reviews/{id}:
    patch:
      tags: [Reviews]
      summary: Update review (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ReviewUpdate' }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Review' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
    delete:
      tags: [Reviews]
      summary: Delete review (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Review' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /photos:
    get:
      tags: [Photos]
      summary: List photos
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Array of photos
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Photo' }
    post:
      tags: [Photos]
      summary: Create photo (uploaded_by = current user)
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PhotoCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Photo' }
  /photos/{id}:
    patch:
      tags: [Photos]
      summary: Update photo (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PhotoUpdate' }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Photo' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
    delete:
      tags: [Photos]
      summary: Delete photo (owner-only)
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Photo' }
        '404':
          description: Not found or not owner
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    Limit:
      name: limit
      in: query
      schema: { type: integer, minimum: 1, maximum: 100, default: 25 }
      description: Page size
    Offset:
      name: offset
      in: query
      schema: { type: integer, minimum: 0, default: 0 }
      description: Offset for pagination
    IdParam:
      name: id
      in: path
      required: true
      schema: { type: string, format: uuid }
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
  schemas:
    Error:
      type: object
      properties:
        error: { type: string }
        message: { type: string }
    AppProfile:
      type: object
      properties:
        id: { type: string, format: uuid }
        email: { type: string, format: email, nullable: true }
        display_name: { type: string, nullable: true }
        location_city: { type: string, nullable: true }
        location_state: { type: string, nullable: true }
        created_at: { type: string, format: date-time, nullable: true }
        updated_at: { type: string, format: date-time, nullable: true }
    Berry:
      type: object
      properties:
        berry_id: { type: string, format: uuid }
        berry_name: { type: string }
        created_at: { type: string, format: date-time, nullable: true }
    Vendor:
      type: object
      properties:
        vendor_id: { type: string, format: uuid }
        vendor_name: { type: string }
        vendor_type:
          type: string
          enum: [supermarket, farmers_market, fruit_stand, other]
        address: { type: string, nullable: true }
        city: { type: string, nullable: true }
        state: { type: string, nullable: true }
        zip_code: { type: string, nullable: true }
        latitude: { type: number, nullable: true }
        longitude: { type: number, nullable: true }
        created_at: { type: string, format: date-time, nullable: true }
        updated_at: { type: string, format: date-time, nullable: true }
    VendorCreate:
      type: object
      required: [vendor_name, vendor_type]
      properties:
        vendor_name: { type: string, minLength: 1, maxLength: 200 }
        vendor_type:
          type: string
          enum: [supermarket, farmers_market, fruit_stand, other]
        address: { type: string }
        city: { type: string }
        state: { type: string }
        zip_code: { type: string }
        latitude: { type: number }
        longitude: { type: number }
    VendorUpdate:
      allOf:
        - $ref: '#/components/schemas/VendorCreate'
      description: All fields optional
    Price:
      type: object
      properties:
        price_id: { type: string, format: uuid }
        vendor_id: { type: string, format: uuid }
        berry_id: { type: string, format: uuid }
        reported_by: { type: string, format: uuid }
        price_per_unit: { type: number }
        unit_type:
          type: string
          enum: [pound, kg, pint, quart, container, each]
        reported_at: { type: string, format: date-time, nullable: true }
        created_at: { type: string, format: date-time, nullable: true }
    PriceCreate:
      type: object
      required: [vendor_id, berry_id, price_per_unit, unit_type]
      properties:
        vendor_id: { type: string, format: uuid }
        berry_id: { type: string, format: uuid }
        price_per_unit: { type: number, minimum: 0 }
        unit_type:
          type: string
          enum: [pound, kg, pint, quart, container, each]
        reported_at: { type: string, format: date-time }
    PriceUpdate:
      type: object
      properties:
        price_per_unit: { type: number, minimum: 0 }
        unit_type:
          type: string
          enum: [pound, kg, pint, quart, container, each]
        reported_at: { type: string, format: date-time }
    Review:
      type: object
      properties:
        review_id: { type: string, format: uuid }
        vendor_id: { type: string, format: uuid }
        berry_id: { type: string, format: uuid }
        reported_by: { type: string, format: uuid }
        rating: { type: integer, minimum: 1, maximum: 5 }
        quality_rating: { type: integer, minimum: 1, maximum: 5, nullable: true }
        freshness_rating: { type: integer, minimum: 1, maximum: 5, nullable: true }
        value_rating: { type: integer, minimum: 1, maximum: 5, nullable: true }
        review_text: { type: string, nullable: true }
        visited_date: { type: string, format: date }
        created_at: { type: string, format: date-time, nullable: true }
    ReviewCreate:
      type: object
      required: [vendor_id, berry_id, rating]
      properties:
        vendor_id: { type: string, format: uuid }
        berry_id: { type: string, format: uuid }
        rating: { type: integer, minimum: 1, maximum: 5 }
        quality_rating: { type: integer, minimum: 1, maximum: 5 }
        freshness_rating: { type: integer, minimum: 1, maximum: 5 }
        value_rating: { type: integer, minimum: 1, maximum: 5 }
        review_text: { type: string }
        visited_date: { type: string, format: date }
    ReviewUpdate:
      allOf:
        - $ref: '#/components/schemas/ReviewCreate'
      description: All fields optional
    Photo:
      type: object
      properties:
        photo_id: { type: string, format: uuid }
        review_id: { type: string, format: uuid, nullable: true }
        vendor_id: { type: string, format: uuid, nullable: true }
        berry_id: { type: string, format: uuid, nullable: true }
        uploaded_by: { type: string, format: uuid }
        photo_url: { type: string, format: uri }
        thumbnail: { type: string, format: uri, nullable: true }
        caption: { type: string, nullable: true }
        uploaded_at: { type: string, format: date-time, nullable: true }
    PhotoCreate:
      type: object
      required: [photo_url]
      properties:
        review_id: { type: string, format: uuid, nullable: true }
        vendor_id: { type: string, format: uuid }
        berry_id: { type: string, format: uuid }
        photo_url: { type: string, format: uri }
        thumbnail: { type: string, format: uri }
        caption: { type: string }
    PhotoUpdate:
      allOf:
        - $ref: '#/components/schemas/PhotoCreate'
      description: All fields optional
security:
  - bearerAuth: []
